services:
  - type: web
    name: panace-api
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: panace-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: BACKEND_CORS_ORIGINS
        value: "https://panace-web.onrender.com,https://panace-finsys.vercel.app"
